<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>World Courier - Clientes</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Semantic UI Library Styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css">
</head>
<body>

<div class="ui container">
    <br>
    <div class="ui secondary menu">
        <div class="header item">World Courier</div>
        <a href="/clientes" class="item">
            Clientes
        </a>
        <a class="item">
            Empleados
        </a>
        <a class="active item">
            Tarifas
        </a>
        <div class="right menu">
            <a href="/logout" class="ui item">
                Logout
            </a>
        </div>
    </div>
    <div class="ui divider"></div>
    <br>
    <div class="ui grid">
        <div class="twelve wide column">
            <form class="ui form" method="post">
                <div class="field">
                    <label>Servicio</label>
                    <input type="text" name="Servicio" placeholder="Servicio">
                </div>
                <div class="field">
                    <label>Ruta</label>
                    <input type="text" name="ruta" placeholder="Ruta">
                </div>
                <div class="field">
                    <label>Flete</label>
                    <input type="text" name="Flete" placeholder="Flete">
                </div>
                <div class="field">
                    <label>Seguro</label>
                    <input type="text" name="Seguro" placeholder="Seguro">
                </div>
                <div class="field">
                    <label>Cliente</label>
                  <div id="ClienteID" class="ui search selection dropdown">
                  <input type="hidden" name="ClienteID">
                    <div class="text">Search</div>
                </div>
                        <div class="field">
                    <label>Almacenaje</label>
                    <input type="text" name="Almacenaje" placeholder="Almacenaje">
                </div>
                    </select>
                </div>
                <button class="ui button red" type="submit">Grabar</button>
            </form>
        </div>

    </div>
</div>

</body>
<script
    src="https://code.jquery.com/jquery-2.2.4.min.js"
    integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
    crossorigin="anonymous"></script>
<!-- Semantc UI JS -->
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js"></script>
<script src="/assets/js/main.js" ></script>
</html>
