<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>World Courier</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <!-- Semantic UI Library Styles -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css">
</head>
<body>

  <div class="ui container">
  <br>
  <div class="ui secondary menu">
    <div class="header item">World Courier</div>
    <a class="active item">
      Home
    </a>
    <a class="item">
      Messages
    </a>
    <a class="item">
      Friends
    </a>
    <div class="right menu">
      <div class="item">
        <div class="ui icon input">
          <input type="text" placeholder="Search...">
          <i class="search link icon"></i>
        </div>
      </div>
      <a href="/logout" class="ui item">
        Logout
      </a>
    </div>
  </div>
  <div class="ui divider"></div>
  <br>
  <div class="ui grid">
    <div class="four wide column">
      <div class="ui secondary vertical pointing fluid menu">
        <a class="item">
          Home
        </a>
        <a class="item">
          Messages
        </a>
        <a class="item active">
          Friends
        </a>
      </div>
    </div>
    <div class="twelve wide column">
      <div class="ui form">
        <div class="field">
          <input type="text" name="first-name" placeholder="First name">
        </div>
        <div class="field">
          <textarea placeholder="Some example text..."></textarea>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous"></script>
<!-- Semantc UI JS -->
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js"></script>

</html>
