<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>World Courier - Clientes</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <!-- Semantic UI Library Styles -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css">
</head>
<body>

  <div class="ui container">
  <br>
  <div class="ui secondary menu">
    <div class="header item">World Courier</div>
    <a href="/clientes" class="active item">
      Clientes
    </a>
    <a href="/empleados" class="item">
      Empleados
    </a>
    <a href="/tarifas" class="item">
      Tarifas
    </a>
     <a href="/pedidos" class="item">
      Pedidos
    </a>
    <div class="right menu">
      <a href="/logout" class="ui item">
        Logout
      </a>
    </div>
  </div>
  <div class="ui divider"></div>
  <br>
  <div class="ui grid">
    <div class="twelve wide column">
      <a class="ui button blue right floated" href="/clientes/create">
        <i class="icon user"></i>
         Nuevo
      </a>
      <div class="ui icon input">
        <i class="search icon"></i>
        <input type="text" placeholder="Buscar...">
      </div>
    </div>

    <div class="twelve wide column" >
      <table class="ui celled table">
        <thead>
        <tr>
            <th>Acciones</th>
          <th>Nombres</th>
          <th>Apellido Paterno</th>
          <th>Apellido Materno</th>
          <th>Tipo Cliente</th>
          <th>DNI</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($clientes as $cliente): ?>
        <tr>
          <td>
            <a class="ui icon button blue" href="/clientes/<?= $cliente["ClienteID"] ?>/edit" >
              <i class="edit icon"></i>
            </a>
            <a class="ui icon button red" href="/clientes/<?= $cliente["ClienteID"] ?>/delete" >
              <i class="delete icon"></i>
            </a>
          </td>
          <td><?= $cliente["Nombre"] ?></td>
          <td><?= $cliente["Apellido_paterno"] ?></td>
          <td><?= $cliente["Apellido_materno"] ?></td>
          <td><?= $cliente["tipo_cliente"] ?></td>
          <td><?= $cliente["DNI"] ?></td>
        </tr>
        <?php endforeach ?>
        </tbody>
        <tfoot>
        <tr><th colspan="6">
            <div class="ui right floated pagination menu">
              <a class="icon item">
                <i class="left chevron icon"></i>
              </a>
              <a class="item">1</a>
              <a class="item">2</a>
              <a class="item">3</a>
              <a class="item">4</a>
              <a class="icon item">
                <i class="right chevron icon"></i>
              </a>
            </div>
          </th>
        </tr></tfoot>
      </table>

    </div>

  </div>
</div>

</body>
<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous"></script>
<!-- Semantc UI JS -->
<script src="https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js"></script>

</html>